enhance fll shell wrapper, give uid and gid to fll.py for permission adjustments

diff --git a/fll b/fll
--- a/fll
+++ b/fll
@@ -1,14 +1,31 @@
 #!/bin/sh -e
 
-CWD=$(dirname $(readlink -f ${0}))
+# Copyright: (C) 2008 Kel Modderman <kel@otaku42.de>
+# License:   GPLv2 or any later version
 
-if [ -f ${CWD}/fll.py ]; then
-	exec /usr/bin/python ${CWD}/fll.py --share ${CWD} ${@}
+# Locate directory we are called from
+THIS_DIR=$(dirname $(readlink -f ${0}))
+
+# Get callers uid and gid for permission adjustment
+USER_UID=$(getent passwd ${USER} | cut -d\: -f3)
+USER_GID=$(getent passwd ${USER} | cut -d\: -f4)
+
+# Locate the real program
+if [ -f ${THIS_DIR}/fll.py ]; then
+	FLL="${THIS_DIR}/fll.py --share ${THIS_DIR}"
+elif [ -f /usr/share/fll/fll.py ]; then
+	FLL="/usr/share/fll/fll.py"
+else
+	echo "Error locating fll.py, aborting." >&2
+	exit 1
 fi
 
-if [ -f /usr/share/fll/fll.py ]; then
-	exec /usr/bin/python /usr/share/fll/fll.py ${@}
+# If --help option is wanted, don't exec as root
+if echo ${*} | egrep -q -w '\-\-help|\-h'; then
+	exec /usr/bin/python ${FLL} --help
 fi
 
-echo "Error locating fll.py, aborting." >&2
-exit 1
+# Exec program as root...
+echo "Requires root!"
+exec su root --command \
+	"/usr/bin/python ${FLL} --uid ${USER_UID} --gid ${USER_GID} ${*}"
